import { useState } from 'react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { Robot, Sparkles, House, Hammer, Wheelchair, Heart } from '@phosphor-icons/react'
import { toast } from 'sonner'
import { useAuth } from '@/lib/auth'

export function AINeighborHelpMachine() {
  const { userProfile, isAuthenticated } = useAuth()
  const [description, setDescription] = useState('')
  const [neighborName, setNeighborName] = useState('')
  const [urgency, setUrgency] = useState<'immediate' | 'soon' | 'planned'>('soon')
  const [isBuilding, setIsBuilding] = useState(false)
  const [generatedPage, setGeneratedPage] = useState('')

  const QUICK_REQUESTS = [
    { icon: House, label: 'New House', category: 'housing', description: 'Need accessible single-level home' },
    { icon: Hammer, label: 'Porch Ramp', category: 'accessibility', description: 'Need wheelchair ramp' },
    { icon: Wheelchair, label: 'Single-Level Convert', category: 'accessibility', description: 'Convert to single level - no elevator' },
    { icon: Heart, label: 'Emergency', category: 'emergency', description: 'Urgent help needed' }
  ]

  const buildPageWithAI = async (category: string, desc: string) => {
    setIsBuilding(true)
    toast.info('🤖 AI building help page...')
    await new Promise(r => setTimeout(r, 2000))
    
    const page = `# Help Request: ${category}\n\nFor: ${neighborName}\nNeeds: ${desc}\nUrgency: ${urgency}\n\nGenerated by AI Neighbor Help Machine`
    setGeneratedPage(page)
    
    await window.spark.kv.set(`help-request-${Date.now()}`, { category, desc, neighborName, urgency })
    toast.success('✅ Help request posted!')
    setIsBuilding(false)
  }

  return (
    <div className="space-y-6">
      <Card className="p-6">
        <Robot size={48} className="mb-4" />
        <h2 className="text-3xl font-bold">AI Neighbor Help Machine</h2>
        <p>Build help requests instantly</p>
      </Card>

      <Card className="p-6">
        <div className="grid grid-cols-2 gap-3">
          {QUICK_REQUESTS.map((req, i) => (
            <Button key={i} onClick={() => buildPageWithAI(req.category, req.description)}>
              <req.icon size={24} className="mr-2" />
              {req.label}
            </Button>
          ))}
        </div>
      </Card>

      <Card className="p-6">
        <Label>Who needs help?</Label>
        <Input value={neighborName} onChange={e => setNeighborName(e.target.value)} />
        
        <Label className="mt-4">What do they need?</Label>
        <Textarea value={description} onChange={e => setDescription(e.target.value)} rows={4} />
        
        <Button className="mt-4" onClick={() => buildPageWithAI('custom', description)} disabled={isBuilding}>
          <Sparkles className="mr-2" />
          Build with AI
        </Button>
      </Card>

      {generatedPage && (
        <Card className="p-6">
          <h3 className="font-bold mb-2">Generated Page</h3>
          <pre className="bg-muted p-4 rounded">{generatedPage}</pre>
        </Card>
      )}
    </div>
  )
}